version: 2

sources:
  - name: pipedrive
    database: postgres
    schema: public
    description: Source data from the PipeDrive CRM system
    tables:
      - name: activity
      - name: activity_types
      - name: deal_changes
      - name: fields
      - name: stages
      - name: users